/// <reference types="node" />

import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs"

import type { ParityKind, ParityResult, VisualOs } from "./visual.types.ts"
import { VisualSettings } from "./VisualSettings.ts"

/****************
 * ### `ParityReport`
 * The parity reports:  collect the spec's `ParityResult` files (`tools/results/visual/<os>/<kind folder>/<browser>/`)
 * into one markdown file per kind, one table per OS and browser, most different first.
 * - `--parity` => `tools/results/visual/parity.md`:  class grammar vs elements
 * - `--static` => `tools/results/visual/static-parity.md`:  static render vs elements
 * - Informational only:  the two sides aren't pixel-identical (headings, wrappers, shorthands;  a static page has no
 *   icon glyphs yet), so a difference is a lead to look at, not a failure.
 * - STATIC:  it reads and writes files, and keeps nothing.
 ****************/
export class ParityReport {
  /** Remove `os`'s previous `kind` results, so the report never mixes runs. */
  static clear(os: VisualOs, kind: ParityKind) {
    rmSync(ParityReport.folder(os, kind), { recursive: true, force: true })
  }

  /** Results folder of `os` and `kind`, relative to `VisualSettings.RESULTS` (where the report lives). */
  static relativeFolder(os: VisualOs, kind: ParityKind): string {
    return `${VisualSettings.osFolder(os)}/${KINDS[kind].folder}`
  }

  /** Write the `kind` report for `oses`;  returns its path. */
  static write(oses: readonly VisualOs[], kind: ParityKind): string {
    const { threshold, ratio } = VisualSettings.PARITY
    const { file, title, command, other, intro } = KINDS[kind]
    const lines = [
      `# ${title}`,
      "",
      `Generated by \`${command}\`, ${new Date().toISOString().slice(0, 16).replace("T", " ")} UTC.`,
      ...intro,
      "",
      `- a pixel differs when a channel differs by more than ${threshold} of 255`,
      `- a pair is listed as DIFFERENT above ${(ratio * 100).toFixed(1)}% differing pixels (size changes count)`,
      "- diff images:  red = differing pixel, over a faded copy of the element render",
      ""
    ]
    for (const os of oses) {
      const folder = ParityReport.folder(os, kind)
      if (!existsSync(folder)) continue
      for (const browser of readdirSync(folder).sort()) {
        const results = readdirSync(`${folder}/${browser}`)
          .filter((name) => name.endsWith(".json"))
          .map((name) => JSON.parse(readFileSync(`${folder}/${browser}/${name}`, "utf8")) as ParityResult)
          .sort((a, b) => b.ratio - a.ratio || a.id.localeCompare(b.id))
        const different = results.filter((result) => result.ratio > ratio)
        const failed = results.filter((result) => result.error)
        lines.push(`## ${VisualSettings.osFolder(os)} / ${browser}`, "")
        lines.push(`${different.length} of ${results.length} pairs differ.`, "")
        if (failed.length) {
          lines.push(`${failed.length} failed (render or capture):`, "")
          for (const result of failed) lines.push(`- \`${result.id}\` (${result.scheme}):  ${result.error}`)
          lines.push("")
        }
        lines.push(
          `| Example | Scheme | ${other} (w x h) | Elements (w x h) | Differing | Diff | Notes |`,
          "|---|---|--:|--:|--:|---|---|"
        )
        for (const result of results) lines.push(ParityReport.row(result))
        lines.push("")
      }
    }
    mkdirSync(VisualSettings.RESULTS, { recursive: true })
    const path = `${VisualSettings.RESULTS}/${file}`
    writeFileSync(path, `${lines.join("\n")}\n`)
    return path
  }

  /** One table row. */
  private static row(result: ParityResult): string {
    const size = ({ width, height }: { width: number; height: number }) => `${width} x ${height}`
    const percent = result.error ? "failed" : `${(result.ratio * 100).toFixed(2)}%`
    const diff = result.diff ? `[diff](${result.diff})` : ""
    const notes = result.error
      ? "failed"
      : result.leftover?.length
        ? `not rendered:  ${result.leftover.map((tag) => `\`${tag}\``).join(", ")}`
        : ""
    return `| \`${result.id}\` | ${result.scheme} | ${size(result.other)} | ${size(result.elements)} | ${percent} | ${diff} | ${notes} |`
  }

  /** Results folder of `os` and `kind`. */
  private static folder(os: VisualOs, kind: ParityKind): string {
    return `${VisualSettings.RESULTS}/${ParityReport.relativeFolder(os, kind)}`
  }
}

/** One kind of parity report (`KINDS`). */
export type ParityReportKind = {
  /** results folder under `tools/results/visual/<os>/` */
  folder: string
  /** report file under `tools/results/visual/` */
  file: string
  /** report heading */
  title: string
  /** the command that writes it */
  command: string
  /** column heading of the side set against the elements */
  other: string
  /** lines under the heading */
  intro: string[]
}

/** What differs per kind:  results folder, report file, wording. */
const KINDS: Record<ParityKind, ParityReportKind> = {
  parity: {
    folder: "parity",
    file: "parity.md",
    title: "Parity:  class grammar vs elements",
    command: "yarn test:visual --parity",
    other: "Classes",
    intro: [
      "Each example's class-grammar original (`examples/<name>.html`) against its element markup",
      "(`examples/elements/<name>.html`), light scheme.  Informational:  the two markups are not pixel-identical."
    ]
  },
  static: {
    folder: "static-parity",
    file: "static-parity.md",
    title: "Static parity:  static render vs elements",
    command: "yarn test:visual --static",
    other: "Static",
    intro: [
      "Each element example (`examples/elements/<name>.html`) rendered statically -- `StaticRender` + `StaticStylesheet`,",
      "no scripts, no `ui-*` element defined (`/static/<family>/<name>.html`) -- against the live elements, light and dark.",
      "Only the families in `tools/visual/StaticFamilies.ts`.  Informational."
    ]
  }
}
