// Spell "parser" class.
//
import isEqual from "lodash/isEqual"
import groupBy from "lodash/groupBy"
import sum from "lodash/sum"

import { Derivative, showWhitespace } from "$/util"
import { P } from "$/parser"

/**
 * Parser for a language ~== named `rules` plus a `tokenizer`, used to `parse()` input into a `Match` tree
 * and `compile()` that into output.
 * - Extends `Derivative` so `rules` can be memoized via `derived()` and invalidated with `clearDerived()`.
 * - `imports` other `Parser`s to combine their `rules` with ours -- see `rules` getter.
 * - Subclass per language, e.g. `SpellParser`; override `tokenizer` / `getScope()` for language-specific
 *   behavior.
 */
export class Parser extends Derivative {
  /** Name of the module this parser (and rules defined in it) belong to. */
  declare module: string | undefined
  /** Rule to parse/compile with if none is specified. */
  declare defaultRule: string
  /** Other parsers whose rules we import. */
  declare imports: Parser[] | undefined

  static {
    Object.defineProperty(this.prototype, "module", { value: undefined, writable: true })
    Object.defineProperty(this.prototype, "defaultRule", { value: "block", writable: true })
  }

  constructor(properties?: ParserProps) {
    super()
    if (properties) Object.assign(this, properties)
  }

  /** Return a clone of this parser with additional `properties` passed in. */
  clone(properties?: ParserProps): this {
    // oxlint-disable-next-line typescript/no-misused-spread
    const allProps = { ...this, ...properties } as Record<string, unknown>
    // clear imports...
    delete allProps.imports
    // ...and journal, which belongs to one project's parse
    delete allProps.journal
    const constructor = this.constructor as new (properties?: ParserProps) => this
    const clone = new constructor(allProps as ParserProps)
    // ...so we can import this parser (and all of ITS imports)
    clone.import(this)
    return clone
  }

  ////////////////
  // ## Tokenizing (a.k.a. "lexical analysis")
  ////////////////

  /**
   * Tokenizer for parsing input string.
   * Override in your subclass if parsing with different policies.
   */
  get tokenizer(): P.Tokenizer {
    return this.derived("tokenizer", () => new P.Tokenizer({ whitespacePolicy: P.WhitespacePolicy.LEADING_ONLY }))
  }

  /**
   * Tokenize `input` as:
   * - string text
   * - a single `Token`
   * - an array (presumably an array of `Tokens`)
   *
   * `ruleName` is there in case you want to tokenize differently for different top-level rules.
   */
  tokenize(input: string | P.Token | P.Token[], ruleName?: string): P.Token[] | undefined {
    if (typeof input === "string") return this.tokenizer.tokenize(input)
    if (input instanceof P.Token) return [input]
    if (Array.isArray(input)) return input
    console.warn("Don't know how to tokenize: ", input)
    return undefined
  }

  ////////////////
  // ## Parsing
  ////////////////

  /**
   * Parsing is done by attempting to match tokens with a set of immutable `rules`.
   * - When doing a top-level `parser.parse()`, we'll create a `scope` object to keep track of the
   *   internal state of the parser as it descends.
   * - Only hard requirement is `scope.parser` must point to a valid `Parser` instance for your language.
   * - Some languages, e.g. `spell`, use a more elaborate `Scope` concept which can keep track of allocated
   *   variables and methods, type definitions, etc.
   */
  getScope(_name?: string): P.Scope {
    return new P.Scope({ parser: this })
  }

  /**
   * Parse `ruleName` rule at head of `input`.
   * - `input` can be a string to tokenize, a single token, or an array of tokens.
   * - Returns `match` generated by `rule.parse()`, or `undefined`.
   */
  parse(
    input: string | P.Token | P.Token[],
    ruleName = this.defaultRule,
    scope = this.getScope()
  ): P.Match | undefined {
    // Bail if we didn't get any tokens back.
    const tokens = this.tokenize(input, ruleName)
    if (!tokens || tokens.length === 0) return undefined

    // Parse the rule or throw an exception if rule not found.
    const rule = scope.getRuleOrDie(ruleName)
    return rule.parse(scope, tokens)
  }

  /**
   * What could come after `input`, a half-typed `ruleName`, e.g. `to` after `set x` -- for editor completion.
   * - Parses `input` in expecting mode:  rules record what they were waiting for where they ran out of tokens.
   *   See `P.Expectations` for what each kind of rule records, and `P.Expectation` for what you get back.
   * - Nothing typed yet => `ruleName` itself.
   * - Side-effect free:  parsing never changes scope, only `commit()` / `mutateScope()` do.
   */
  expectedAfter(
    input: string | P.Token | P.Token[],
    ruleName = this.defaultRule,
    scope = this.getScope()
  ): P.Expectation[] {
    const tokens = this.tokenize(input, ruleName) ?? []
    const rule = scope.getRuleOrDie(ruleName)
    return P.Expectations.collect(() => {
      if (tokens.length) rule.parse(scope, tokens)
      else P.Expectations.current!.expect(rule)
    })
  }

  /**
   * Lock in `match`, parsed on its own and being kept, e.g. by a rule unit test:  apply its scope changes.
   * - Default just calls `rule.mutateScope()`.  Languages override, e.g. `SpellParser` also commits
   *   inline statements -- see `SP.commitStatement()`.
   * - NOTE: only for matches parsed OUTSIDE a language's own block parsing, which commits each line itself.
   */
  commit(match: P.Match) {
    match.rule.mutateScope(match)
  }

  ////////////////
  // ## Forward declarations
  ////////////////

  /**
   * Names of the types `text` declares, found WITHOUT parsing it, e.g. `["card"]` for `a card is a thing`.
   * - Why:  so a line can name a type declared further down, or in a later file -- see `stubDeclaredTypes()`.
   * - A cheap scan, not a parse:  a stray extra name just makes one more type known.
   * - Default:  none.  Languages override, e.g. `SpellParser`.
   */
  declaredTypes(_text: string): string[] {
    return []
  }

  /**
   * Stub each type `texts` declare (`declaredTypes()`) which `scope` doesn't know yet.
   * - Run BEFORE a project's files parse, so a line above a type's declaration knows the type too,
   *   e.g. `if the pile is a foundation`.
   * - Its declaration then `claim()`s the stub -- see `P.TypeScope.getOrStub()`.
   * - Through `scope.types.add()`:  journaled, if there's a journal.
   * - Returns the names found, in order:  `P.IncrementalProject` re-parses everything when an edit changes them.
   */
  stubDeclaredTypes(scope: P.Scope, texts: string[]): string[] {
    const names = texts.flatMap((text) => this.declaredTypes(text))
    for (const name of names) if (!scope.types?.get(name)) scope.types?.add({ name, stub: true })
    return names
  }

  ////////////////
  // ## Incremental parsing -- see `P.IncrementalParse`
  ////////////////

  /**
   * Root `BlockToken` for a whole file's `text`:  its `tokens` are the file's top-level items.
   * - `undefined` if we don't break files into indented blocks, so can't re-parse them incrementally.
   */
  tokenizeRoot(text: string): P.BlockToken | undefined {
    const [root] = this.tokenize(text, "block") ?? []
    return root instanceof P.BlockToken ? root : undefined
  }

  /**
   * Parse the top-level item at the start of `items`, e.g. a line plus any indented body it takes.
   * - Returns its match, whose `length` says how many of `items` it took, or `undefined` if it didn't parse.
   * - Default:  `undefined`, i.e. can't parse item by item.  Languages with indented blocks override.
   */
  parseItem(_scope: P.Scope, _items: P.Token[]): P.Match | undefined {
    return undefined
  }

  /**
   * Is top-level `item` broken, e.g. has parse errors?  `P.IncrementalParse` can keep a broken item's last
   * working declarations -- see `keepLastGood`.
   * - Default:  only if it didn't parse at all.
   */
  isBrokenItem(item: P.Match | undefined): boolean {
    return !item
  }

  /**
   * Journal mark taken just before top-level `item`'s indented body was parsed, if it has one.
   * - `P.IncrementalParse` rewinds to it to re-parse just the body.  Default:  `undefined`.
   */
  getBodyMark(_item: P.Match): P.JournalMark | undefined {
    return undefined
  }

  /**
   * Re-parse ONLY the indented `body` of top-level `item`, keeping its header line's match as-is.
   * - Shared state has already been rewound to `getBodyMark(item)`.
   * - Returns a new match for the whole item, or `undefined` if that's not safe, e.g. the body changes
   *   more than its own scope -- caller then re-parses from the item on.
   * - Default:  never safe.  Languages with bodies override, e.g. `SpellParser`.
   */
  reparseBody(_item: P.Match, _body: P.BlockToken): P.Match | undefined {
    return undefined
  }

  /**
   * File match for `root` from the matches of its top-level `items`, as a full parse would build it.
   * - Default:  `undefined`, i.e. can't.  Languages which support `reparseBody()` override.
   */
  assembleFile(_scope: P.Scope, _root: P.BlockToken, _items: P.Match[]): P.Match | undefined {
    return undefined
  }

  /**
   * Parse `input` and return the resulting output (source code for language parsers).
   * - If one string argument, compiles as `"block"`.
   * - Throws if not parseable.
   */
  compile(input: string | P.Token | P.Token[], ruleName = this.defaultRule, scope = this.getScope()): unknown {
    const match = this.parse(input, ruleName, scope)
    if (!match) {
      throw new P.ParserError({
        message: "Can't parse input",
        context: this,
        activity: "compile",
        params: { input, ruleName, scope }
      })
    }
    return match.compile()
  }

  ////////////////
  // ## Rules
  ////////////////

  /**
   * Private map of all of our rules, NOT including rules from imports.
   * - Use `parser.rules` to get ALL rules, including those from imports.
   */
  #ownRules: P.RuleMap = {}

  /**
   * Records every rule added while parsing, so incremental parsing can take it back -- see `P.ParseJournal`.
   * - `undefined` => nothing's recorded.  Set by whoever wants incremental parsing, e.g. `P.IncrementalProject`.
   * - Scope lists record themselves here too, as `scope.parser.journal`.
   * - NOTE: NOT copied by `clone()`.
   */
  journal: P.ParseJournal | undefined

  /** All rules, including those merged in from `imports`. */
  get rules(): P.RuleMap {
    return this.derived("rules", () => {
      if (!this.imports) return { ...this.#ownRules }
      return this.mergeRuleSets(this.#ownRules, ...this.imports.map((parser) => parser.rules))
    })
  }

  /**
   * Setting `rules` through assignment `addRule()`s each one, adding to our existing rules.
   * - You'll typically set default rules when initializing a parser:
   *   `const myParser = new Parser({ module: "xxx", rules: [some_rule, other_rule] })`.
   * - Order matters:  when two rules tie, the LATER one wins.
   */
  set rules(rules: P.RuleInput[]) {
    this.clearDerived("rules")
    rules.forEach((rule) => this.addRule(rule))
  }

  /** Return a named rule from our parser. Throws if not found. */
  getRuleOrDie(ruleName: string): P.Rule {
    const rule = this.rules[ruleName]
    if (!rule)
      throw new P.ParserError({
        message: `Rule '${ruleName}' not found.`,
        context: this,
        activity: "getRuleOrDie",
        params: { ruleName }
      })
    return rule
  }

  /**
   * Add a `rule` to our list of rules!
   * - Rule CLASS is `instantiate()`d into one frozen instance, added under its name + aliases, plus
   *   `_testable_` if it has tests.  Register a class once per `syntax` if it has several.
   *   Pass its `definition` -- normally just `syntax` + `tests`, the rest lives on the class as `@proto static` --
   *   as second argument, type-checked against that class's props:  `parser.addRule(give, { syntax: "give {thing}" })`.
   * - Rule INSTANCE is added under `ruleName`, defaulting to `rule.name`.
   * - Converts to `P.Group` on re-defining the same rule.
   * - Throws on anything unusable, e.g. bad `syntax` -- better at startup than a mystery parse failure later.
   */
  addRule<RuleType extends P.Rule>(rule: Class<RuleType>, definition?: P.DefinitionFor<RuleType>): P.Rule | undefined
  addRule(rule: P.Rule | P.RuleConstructor, ruleName?: string | string[]): P.Rule | undefined
  addRule(
    rule: P.Rule | P.RuleConstructor,
    namesOrDefinition?: string | string[] | P.RuleDefinitionProps
  ): P.Rule | undefined {
    // Clear memoized "rules" so we'll recalculate them
    this.clearDerived("rules")

    // Second argument is either explicit name(s) or, for a rule class, its definition props.
    const isNames = typeof namesOrDefinition === "string" || Array.isArray(namesOrDefinition)
    let ruleName = isNames ? namesOrDefinition : undefined

    // If rule is a Rule subclass, instantiate it and add the instance under all of its names
    if (typeof rule === "function") {
      const ruleClass = rule as unknown as typeof P.Rule
      const definition: P.RuleDefinitionProps = isNames ? {} : { ...namesOrDefinition }
      if (this.module) definition.module = this.module
      const instance = ruleClass.instantiate(definition)
      if (!instance) return undefined
      const names: string[] = ruleName ? [ruleName].flat() : instance.names
      return this.addRule(instance, instance.tests ? [...names, "_testable_"] : names)
    }

    // If we didn't get a ruleName, try `rule.name`
    if (!ruleName) {
      if (rule.name) ruleName = rule.name
    }
    if (!ruleName) {
      throw new P.ParserError({
        message: `You must set 'rule.name' or pass an explicit ruleName.`,
        context: this,
        activity: "addRule",
        params: { rule, ruleName }
      })
    }

    if (!(rule instanceof P.Rule)) {
      throw new P.ParserError({
        message: "addRule() expects a Rule class or instance.",
        context: this,
        activity: "addRule",
        params: { rule, ruleName }
      })
    }

    // If we got an array of `ruleName`s, recursively add under each name with the same `rule`.
    if (Array.isArray(ruleName)) {
      this.getNamesForRule(rule, ruleName).forEach((name) => this.addRule(rule, name))
    }
    // Add to our list of rules
    else {
      const previous = this.#ownRules[ruleName]
      this.mergeRule(this.#ownRules, ruleName, rule)
      const next = this.#ownRules[ruleName]
      this.journal?.record({
        undo: () => this.setOwnRule(ruleName, previous),
        redo: () => this.setOwnRule(ruleName, next)
      })
    }

    return rule
  }

  /** Set (or with no `rule`, remove) one of our own rules directly, e.g. to undo `addRule()`. */
  private setOwnRule(ruleName: string, rule: P.Rule | undefined) {
    if (rule) this.#ownRules[ruleName] = rule
    else delete this.#ownRules[ruleName]
    this.clearDerived("rules")
  }

  /**
   * All names `rule` should be registered under, given the `names` it asked for.
   * - Override to add language-specific collections, e.g. spell's `operand`.
   */
  protected getNamesForRule(_rule: P.Rule, names: string[]): string[] {
    return names
  }

  /** Add rules from other `Parser`s (`imports`) to this parser. */
  import(...imports: Parser[]) {
    // Clear memoized "rules" so we'll recalculate them
    this.clearDerived("rules")
    this.imports = [...(this.imports || []), ...imports]
  }

  /** Merge all rule `sources` together into a new rules map. */
  mergeRuleSets(...sources: P.RuleMap[]): P.RuleMap {
    const rules = { ...sources[0] }
    for (let i = 1, last = sources.length; i < last; i++) {
      const source = sources[i]!
      Object.keys(source).forEach((ruleName) => this.mergeRule(rules, ruleName, source[ruleName]!))
    }
    return rules
  }

  /**
   * Merge a single `rule` into map of `rules` by `ruleName`.
   * If `rules` already has a rule with that name:
   * - if `rules[ruleName]` is a `P.Group`, we'll just add the new rule to the group,
   * - or we'll convert `rules[ruleName]` to a group with the original + new rules.
   */
  mergeRule(map: P.RuleMap, ruleName: string, rule: P.Rule) {
    const existing = map[ruleName]
    if (!existing) {
      // Always clone groups when adding.
      if (rule instanceof P.Group) rule = rule.clone()
      map[ruleName] = rule
      return
    }

    // Merge existing rule and rule passed in as a new Group
    const group =
      existing instanceof P.Group ? existing.clone() : new P.Group({ rules: [existing], matchGroup: ruleName })
    map[ruleName] = group

    // If rule is ALSO a group with the same matchGroup, merge the groups.
    if (rule instanceof P.Group && rule.matchGroup === existing.matchGroup) group.addChoice(this, ...rule.rules)
    else group.addChoice(this, rule)
  }

  ////////////////
  // ## Rulex -- regex-like syntax which rule classes use for `static syntax`
  ////////////////

  /**
   * `RulexParser`, used to create rules from regex-like syntax.
   * - To avoid circular import problems, we don't link to this by default.
   * - If you have a language which needs rulex functionality, inject it with
   *   `import $/parser/rulex`.
   */
  static rulexParser: P.RulexParser | undefined

  ////////////////
  // ## Testing
  ////////////////

  /**
   * Do a timing test for all of the `testable` rules of this parser.
   * - Pass `moduleName` to restrict to just those defined by a module.
   * - Runs the full test once to warm up the rules, then runs 20 more times to get an average
   *   time once we're warmed up.
   */
  speedTest(moduleName = ""): P.SpeedTestResults {
    console.group(`Speed test for ${moduleName ? `module ${moduleName}` : "all modules"}`)
    // Run the test once first to warm up the rules.
    const { time: initialTime, ...results } = this.testRules(moduleName, false)
    console.debug(`Initial run`)
    console.debug(`     time: ${initialTime} msec`)
    console.debug(`   passed: ${results.pass} test(s)`)
    console.debug(`   failed: ${results.fail} test(s)`)

    // Run 20 separate times to average time after warmup.
    console.debug(`Subsequent runs:`)
    const runCount = 20
    const times: number[] = []
    for (let index = 1; index <= runCount; index++) {
      const runTime = this.testRules(moduleName, false).time
      console.debug(`   run #${index}: ${runTime} msec`)
      times.push(runTime)
    }

    const average = sum(times) / runCount
    const min = Math.min(...times)
    const max = Math.max(...times)

    console.debug(`      min: ${min} msec`)
    console.debug(`      max: ${max} msec`)
    console.debug(`  average: ${average} msec`)
    console.groupEnd()

    return { ...results, initialTime, average, min, max }
  }

  /**
   * `compiled` output as a rule's tests expect it -- as is, unless a language says otherwise.
   * - e.g. `SpellParser` drops the declarations comments a project's compiled JS carries:  a rule's tests are
   *   about its code.
   * - Used by `testRules()` and the vitest harness, `unitTestModuleRules()`.
   */
  normalizeTestOutput(compiled: unknown): unknown {
    return compiled
  }

  /**
   * Test `testable` rules for this parser.
   * - Pass `moduleName` to restrict to just those defined by a module.
   * - By default we output debug info about the run.
   * - Pass `false` to `debug` to skip debug output.
   */
  testRules(moduleName?: string, debug = true): P.TestResults {
    const t0 = Date.now()
    const results: P.TestResults = {
      pass: 0, // number of tests that passed
      fail: 0, // number of tests that failed
      failed: [], // input tests that failed as `{ ruleName, input }`
      time: 0
    }
    if (debug) {
      if (moduleName) console.group("Testing rules for module", moduleName)
      else console.group("Testing all parser rules")
    }

    // Get all of the testable rules in this parser.
    const testable = this.rules._testable_
    let rules: P.Rule[] | undefined = testable instanceof P.Group ? testable.rules : testable ? [testable] : undefined
    if (moduleName && rules) rules = groupBy(rules, "module")[moduleName]
    if (!rules) {
      if (debug) console.debug("no testable rules found")
    } else {
      rules.forEach(({ name: ruleName, tests: testBlocks }) => {
        if (!testBlocks) return
        if (debug) console.group("testing rule", ruleName)

        testBlocks.forEach(({ compileAs = ruleName, tests, beforeEach }) => {
          if (debug && compileAs !== ruleName) console.group(`testing as ${compileAs}`)

          tests.forEach((test) => {
            // javascript only:  the speed test times the parser, so what it does mustn't grow with each writer
            const { input, js: output, skip } = P.normalizeRuleTest(test)
            if (skip || input === "") return

            // Create a new scope for the run, so we don't muck with the main parser.
            // Run `beforeEach` code if provided to seed variables, etc.
            const scope = this.getScope("test")
            if (beforeEach) beforeEach(scope)

            let result: unknown
            try {
              const match = scope.parse(input, compileAs!)
              if (match) {
                scope.parser?.commit(match)
                result = this.normalizeTestOutput(match.compile())
              }
            } catch (e) {
              result = e
            }
            if (isEqual(result, output) || (result instanceof Error && output === undefined)) {
              if (debug) console.debug("PASS:  ", showWhitespace(input))
              results.pass++
            } else {
              if (debug) {
                console.debug(
                  "FAIL:  ",
                  showWhitespace(input),
                  "\n  EXPECTED: ",
                  typeof output === "string" ? showWhitespace(output) : output,
                  "\n       GOT: ",
                  typeof result === "string" ? showWhitespace(result) : result
                )
              }
              results.fail++
              results.failed.push({ ruleName, input, expected: output, result })
            }
          })
          if (debug && compileAs !== ruleName) console.groupEnd()
        })
        if (debug) console.groupEnd()
      })
    }
    if (debug) console.groupEnd()

    results.time = Date.now() - t0
    return results
  }
}

/** Constructor props for `Parser`. */
export type ParserProps = {
  /** Name of the module this parser (and rules defined in it) belong to. */
  module?: string
  /** Rule to parse/compile with if none is specified. */
  defaultRule?: string
  /** Rule classes (or instances) to add immediately, via `addRule()`. */
  rules?: P.RuleInput[]
  /** Other parsers whose rules to import. */
  imports?: Parser[]
}
