/**
 * Generates `src/languages/spell.<lang>.ts` (+ `.bundle.js`):  the PRE-COMPILED spell highlighter `<ui-code language="spell">` loads.
 * - Run with `yarn gen:spell` (`tsc -p scripts && tsx scripts/gen-spell.ts`) after changing spell's grammar or
 *   `packages/spell/src/highlight/`;  the files are committed, so `ui` builds and tests without building spell.
 * - Why a bundle:  `ui` NEVER imports spell's source (root `AGENTS.md`, "Overview");  this generated file is the
 *   one exception.  It holds the parser and spell's rules (`packages/spell/src/highlight/browser.ts`, the entry).
 * - `platform: "browser"`:  esbuild refuses a node built-in, so a bundle that builds is browser-safe.
 * - One file per language;  only English exists today (`LANGUAGES`).
 * - Writes three files per language:
 *   - `spell.<lang>.bundle.js`:  the bundle (`.bundle`:  TS would map `./spell.<lang>.js` to the wrapper itself)
 *   - `spell.<lang>.bundle.d.ts`:  its type, for `tsc`
 *   - `spell.<lang>.ts`:  the wrapper `SpellLanguage` imports.  Why:  it imports `SourceError` (built into
 *     `core.js`) and uses it, so the chunk depends on core and Rolldown keeps its runtime helpers there -- a chunk
 *     needing them on its own splits a `rolldown-runtime-<hash>.js` EVERY page loads (see
 *     `src/runtime/TemporalPolyfill.ts`)
 */
import { readFileSync, statSync, writeFileSync } from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

import { build, type Plugin } from "esbuild"

/** The repo root. */
const REPO = fileURLToPath(new URL("../../../", import.meta.url))

/** Spell's browser entry, and the tsconfig whose `paths` resolve its `$/...` imports. */
const ENTRY = path.join(REPO, "packages/spell/src/highlight/browser.ts")
const TSCONFIG = path.join(REPO, "packages/spell/tsconfig.json")

/** Where the bundles go. */
const OUTPUT = fileURLToPath(new URL("../src/languages/", import.meta.url))

/** Languages to build, each `spell.<lang>.js`. */
const LANGUAGES = ["en"]

/** Spell's version, for `__PACKAGE_VERSION__`. */
const VERSION = (
  JSON.parse(readFileSync(path.join(REPO, "packages/spell/package.json"), "utf8")) as { version: string }
).version

/**
 * `react-dom`, stubbed:  `$/util`'s `Observable` pulls in react-easy-state, whose React platform imports `react-dom`
 * for `unstable_batchedUpdates` alone -- ~127 kB minified that highlighting never renders with.  The stub batches by
 * just running the function, as easy-state does without React.
 */
const REACT_DOM_STUB: Plugin = {
  name: "react-dom-stub",
  setup(builder) {
    builder.onResolve({ filter: /^react-dom$/ }, () => ({ path: "react-dom", namespace: "react-dom-stub" }))
    builder.onLoad({ filter: /.*/, namespace: "react-dom-stub" }, () => ({
      contents:
        "export const unstable_batchedUpdates = (fn, ...args) => fn(...args)\nexport default { unstable_batchedUpdates }",
      loader: "js"
    }))
  }
}

for (const language of LANGUAGES) {
  const outfile = path.join(OUTPUT, `spell.${language}.bundle.js`)
  await build({
    entryPoints: [ENTRY],
    outfile,
    bundle: true,
    format: "esm",
    platform: "browser",
    target: "es2022",
    minify: true,
    // rules and tokens are looked up by CLASS NAME (`Rule 'sequence' not found` without it)
    keepNames: true,
    legalComments: "none",
    tsconfig: TSCONFIG,
    define: { "process.env.NODE_ENV": '"production"', __PACKAGE_VERSION__: JSON.stringify(VERSION) },
    plugins: [REACT_DOM_STUB],
    banner: {
      js: `/* GENERATED by \`yarn gen:spell\` (packages/ui/scripts/gen-spell.ts) from @spell-app/spell ${VERSION}:  NEVER edit. */`
    },
    logLevel: "warning"
  })
  writeFileSync(path.join(OUTPUT, `spell.${language}.bundle.d.ts`), declaration(language))
  writeFileSync(path.join(OUTPUT, `spell.${language}.ts`), wrapper(language))
  console.log(`wrote ${path.relative(REPO, outfile)}:  ${(statSync(outfile).size / 1024).toFixed(0)} kB`)
}

/** `spell.<language>.bundle.d.ts`:  the bundle's default export, a `CodeLanguage` with a `highlight()`. */
function declaration(language: string): string {
  return [
    `/* GENERATED by \`yarn gen:spell\` (packages/ui/scripts/gen-spell.ts):  NEVER edit. */`,
    ``,
    `/** Spell's highlighter (${language}):  highlight.js-scoped spans of a spell snippet. */`,
    `declare const highlighter: { highlight(code: string): { start: number; end: number; kind: string }[] }`,
    `export default highlighter`,
    ``
  ].join("\n")
}

/** `spell.<language>.ts`:  the chunk `SpellLanguage` loads, anchored to `core` -- see the file docs. */
function wrapper(language: string): string {
  return [
    `/* GENERATED by \`yarn gen:spell\` (packages/ui/scripts/gen-spell.ts):  NEVER edit. */`,
    ``,
    `// Import directly:  \`SourceError\` anchors this chunk to core (see gen-spell.ts)`,
    `import { SourceError } from "$/ui/runtime/runtime.types"`,
    ``,
    `import highlighter from "./spell.${language}.bundle.js"`,
    ``,
    `if (typeof highlighter?.highlight !== "function") {`,
    `  throw new SourceError("render", "spell.${language}.bundle.js has no highlight():  run \`yarn gen:spell\`")`,
    `}`,
    ``,
    `export default highlighter`,
    ``
  ].join("\n")
}
