import { existsSync, readFileSync } from "node:fs"
import { join } from "node:path"

import type { SiteAttribute, SiteDataFile, SiteTag } from "../src/docs-components/docs-components.types.ts"
import type { CustomElementsManifest, HtmlCustomData } from "./tools.types.ts"

/**
 * The two STANDARD element descriptions, from the site data (`site/_data/components.json`, every vocabulary):
 * - `custom-elements.json`:  a Custom Elements Manifest (schema 2.1), what web-component tools read (Storybook, linters,
 *   IDE plugins, Claude);  `package.json`'s `customElements` points at it
 * - `html-custom-data.json`:  VS Code's HTML custom data (`html.customData`):  autocomplete and hover docs for every
 *   `<ui-*>` tag, attribute and value in any `.html` file;  the repo's `.vscode/settings.json` loads it
 * - Written by `yarn site:data` beside `components.json` (committed:  editors read them with no build);
 *   `tools/DesignExport.test.ts` fails while they're stale.
 * - Both list COMPONENT tags only, not the doc-only `<ui-docs-*>`.
 * - Why not the `custom-elements-manifest analyze` script (`yarn manifest`):  it reads classes, and our attributes,
 *   events and slots live in the vocabulary objects, which it can't see.
 */
export class ElementManifests {
  /** site data, as `yarn site:data` builds it */
  readonly data: SiteDataFile
  /** `packages/ui`, absolute:  where element class files are looked up (`className()`) */
  readonly uiFolder: string

  constructor(data: SiteDataFile, uiFolder: string) {
    this.data = data
    this.uiFolder = uiFolder
  }

  /**
   * Both files as `yarn site:data` writes them, `[path, text]`, into `dataFolder` (`site/_data/`).
   * - `JSON.stringify(..., 2)`:  oxfmt skips `site/_data/`, so the bytes stay ours and the staleness test can compare.
   */
  outputs(dataFolder: string): [file: string, text: string][] {
    return [
      [join(dataFolder, "custom-elements.json"), JSON.stringify(this.customElements(), null, 2) + "\n"],
      [join(dataFolder, "html-custom-data.json"), JSON.stringify(this.htmlCustomData(), null, 2) + "\n"]
    ]
  }

  /** The Custom Elements Manifest:  one module per family (its `index.ts`, which defines every tag of it). */
  customElements(): CustomElementsManifest {
    const folders = [...new Set(this.data.components.map((tag) => tag.folder))].sort()
    return {
      schemaVersion: "2.1.0",
      readme:
        "Spell UI:  Fomantic UI's vocabulary as `ui-*` custom elements.  Generated by `yarn site:data` -- do not edit.",
      modules: folders.map((folder) => {
        const path = `src/components/${folder}/index.ts`
        const tags = this.data.components.filter((tag) => tag.folder === folder)
        const family = this.data.families[folder]
        return {
          kind: "javascript-module",
          path,
          declarations: tags.map((tag) => this.declaration(tag, tag.main ? family?.tokens : undefined)),
          exports: tags.flatMap((tag) => {
            const declaration = { name: this.className(tag), module: path }
            return [
              { kind: "js", name: declaration.name, declaration },
              { kind: "custom-element-definition", name: tag.tag, declaration }
            ]
          })
        }
      })
    }
  }

  /** VS Code's HTML custom data:  every component tag, its attributes and their values, as markdown docs. */
  htmlCustomData(): HtmlCustomData {
    return {
      version: 1.1,
      tags: this.data.components.map((tag) => ({
        name: tag.tag,
        description: { kind: "markdown", value: ElementManifests.tagMarkdown(tag) },
        attributes: tag.attributes
          .filter((attribute) => attribute.kind !== "json")
          .flatMap((attribute) =>
            [attribute.name, ...(attribute.aliases ?? [])].map((name) => ({
              name,
              description: {
                kind: "markdown" as const,
                value: ElementManifests.attributeMarkdown(
                  attribute,
                  name === attribute.name ? undefined : attribute.name
                )
              },
              ...(ElementManifests.values(attribute).length && {
                values: ElementManifests.values(attribute).map((value) => ({ name: value }))
              })
            }))
          )
      }))
    }
  }

  ////////////////
  // ## Declarations
  ////////////////

  /** One tag's class declaration;  `tokens`:  its family's CSS custom properties (on the main tag only). */
  private declaration(tag: SiteTag, tokens?: readonly { name: string; default: string; description?: string }[]) {
    const attributes = tag.attributes.filter((attribute) => attribute.kind !== "json")
    const properties = tag.attributes.filter((attribute) => attribute.kind === "json")
    return {
      kind: "class",
      name: this.className(tag),
      tagName: tag.tag,
      customElement: true,
      summary: tag.description ?? "",
      description: [tag.description, tag.aka.length ? `Also known as:  ${tag.aka.join(", ")}.` : ""]
        .filter(Boolean)
        .join("\n\n"),
      attributes: attributes.map((attribute) => ({
        name: attribute.name,
        description: attribute.description,
        type: { text: ElementManifests.typeText(attribute) },
        ...(attribute.default !== undefined &&
          attribute.default !== null && { default: JSON.stringify(attribute.default) }),
        fieldName: attribute.property ?? ElementManifests.camel(attribute.name)
      })),
      members: properties.map((attribute) => ({
        kind: "field",
        name: attribute.property ?? ElementManifests.camel(attribute.name),
        description: `${attribute.description}  A JS property (rich data), not an attribute.`,
        type: { text: "unknown" }
      })),
      events: tag.events.map((event) => ({
        name: event.name,
        description: event.description + (event.cancelable ? "  Cancelable:  `preventDefault()` vetoes it." : ""),
        type: { text: `CustomEvent<${event.detail}>` }
      })),
      slots: tag.slots.map((slot) => ({ name: slot.name, description: slot.description })),
      cssParts: tag.parts.map((part) => ({ name: part.name, description: part.description })),
      cssStates: tag.states.map((state) => ({ name: state.name, description: state.description })),
      cssProperties: (tokens ?? []).map((token) => ({
        name: token.name,
        default: token.default,
        ...(token.description && { description: token.description })
      }))
    }
  }

  /**
   * `tag`'s class name:  `UI<Name>` by convention (`ui-breadcrumb-section` => `UIBreadcrumbSection`), checked against
   * its family folder;  else the class the family barrel names ending in `<Name>` (`ui-event` => `UIFeedEvent`).
   */
  className(tag: SiteTag): string {
    const name = `UI${ElementManifests.pascal(tag.tag)}`
    const folder = join(this.uiFolder, "src/components", tag.folder)
    if ([".tsx", ".ts"].some((extension) => existsSync(join(folder, name + extension)))) return name
    const barrel = join(folder, "index.ts")
    if (!existsSync(barrel)) return name
    const found = readFileSync(barrel, "utf8").match(new RegExp(`\\bUI\\w*${ElementManifests.pascal(tag.tag)}\\b`))
    return found?.[0] ?? name
  }

  ////////////////
  // ## Attribute text (shared with `DesignComponents`)
  ////////////////

  /**
   * An attribute's TypeScript type, as text:  `boolean` for a key-only flag, a string union for a value set,
   * `boolean | "left" | "right"` for one that's either, `string` / `number` otherwise.
   */
  static typeText(attribute: SiteAttribute): string {
    const values = ElementManifests.values(attribute).map((value) => JSON.stringify(value))
    switch (attribute.kind) {
      case "keyOnly":
      case "boolean":
        return "boolean"
      case "keyOrValueAndKey":
        return ["boolean", ...values].join(" | ")
      case "number":
        return "number"
      case "json":
        return "unknown"
      case "multiple":
        return "string"
      case "width":
        return values.length ? [...values, "string"].join(" | ") : "string"
      default:
        return values.length ? values.join(" | ") : "string"
    }
  }

  /** Whether an attribute is a plain on / off flag:  present or absent, no value. */
  static isFlag(attribute: SiteAttribute): boolean {
    return attribute.kind === "keyOnly" || attribute.kind === "boolean"
  }

  /** The values an attribute takes, for completion:  its value set (`multiple`:  each word of it). */
  static values(attribute: SiteAttribute): readonly string[] {
    return ElementManifests.isFlag(attribute) ? [] : (attribute.values ?? [])
  }

  /** What an attribute takes, in words:  `flag`, `` `left` · `right` ``, `string` ... */
  static valueWords(attribute: SiteAttribute): string {
    const values = ElementManifests.values(attribute).map((value) => `\`${value}\``)
    switch (attribute.kind) {
      case "keyOnly":
      case "boolean":
        return "flag (present / absent)"
      case "keyOrValueAndKey":
        return `flag, or ${values.join(" · ")}`
      case "multiple":
        return `space-separated:  ${values.join(" · ")}`
      case "width":
        return `${values.length ? `${values[0]}-${values.at(-1)}` : "columns"}, a fraction (\`1/4\`) or a percentage`
      case "json":
        return "JS property (rich data)"
      case "icon":
        return "icon name"
      case "number":
        return "number"
      default:
        return values.length ? values.join(" · ") : "text"
    }
  }

  /** A tag's hover docs:  description, also-known-as, slots and events. */
  static tagMarkdown(tag: SiteTag): string {
    const lines = [tag.description ?? "", ""]
    if (tag.aka.length) lines.push(`Also known as:  ${tag.aka.join(", ")}.`, "")
    if (tag.slots.length)
      lines.push("**Slots:**  " + tag.slots.map((slot) => (slot.name ? `\`${slot.name}\`` : "default")).join(", "), "")
    if (tag.events.length) lines.push("**Events:**  " + tag.events.map((event) => `\`${event.name}\``).join(", "), "")
    return lines.join("\n").trim()
  }

  /** An attribute's hover docs;  `aliasOf`:  the canonical name, when this is an alias. */
  static attributeMarkdown(attribute: SiteAttribute, aliasOf?: string): string {
    const lines = [aliasOf ? `Alias of \`${aliasOf}\`.  ${attribute.description}` : attribute.description]
    lines.push("", `Takes:  ${ElementManifests.valueWords(attribute)}`)
    if (attribute.default !== undefined && attribute.default !== null) lines.push(`Default:  \`${attribute.default}\``)
    return lines.join("\n")
  }

  /** `ui-breadcrumb-section` => `BreadcrumbSection`. */
  static pascal(tag: string): string {
    return tag
      .replace(/^ui-/, "")
      .split("-")
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
      .join("")
  }

  /** `active-text` => `activeText`. */
  static camel(name: string): string {
    return name.replace(/-([a-z])/g, (_, letter: string) => letter.toUpperCase())
  }
}
