import { existsSync, readdirSync, readFileSync } from "node:fs"
import { join } from "node:path"
import { parseHTML } from "linkedom"

import { PageOutline } from "../src/docs-components/ui-docs-search/PageOutline.ts"
import type { SiteSearchFile, SiteSearchPage } from "../src/docs-components/docs-components.types.ts"

/**
 * Builds the Spell UI site's search file, `site/_data/search.json` (`SiteSearchFile`):  every page's title and
 * sections, read from the page FILES' markup, for `<ui-docs-search>`'s jumps to other pages.
 * - Run by `yarn site:data` (`scripts/gen-site-data.ts`, through `SiteDataBuilder.searchText()`) beside
 *   `components.json`;  `tools/SiteDataBuilder.test.ts` fails while it's stale:  rerun after adding, renaming or moving
 *   a section (`yarn site:sections` included).
 * - What a section is, its title, parent and tab:  `PageOutline.sections()`, the SAME rules the element reads the page
 *   shown with, run here on linkedom (a DOM in node), read only.
 * - Page title:  its `main`'s `data-toc-header`, else its `<title>` without ` | Spell UI`;  a component page
 *   (`components/ui-*.html`) names the tag it documents (its file name:  a family's main tag, or a sub-tag with its
 *   own page):  the search lists it as that component, not as a page.
 * - Deterministic:  pages in a fixed order (`pageFiles()`), sections in document order, no dates.
 */
export class SiteSearchBuilder {
  /** Suffix of every page's `<title>`, dropped when a title falls back to it. */
  static readonly TITLE_SUFFIX = / \| Spell UI$/

  /** `packages/ui/site/`. */
  readonly site: string

  constructor(site: string) {
    this.site = site
  }

  /** The whole file, as data. */
  build(): SiteSearchFile {
    return {
      $comment:
        "GENERATED by `yarn site:data` (packages/ui, scripts/gen-site-data.ts, tools/SiteSearchBuilder.ts) from the " +
        "site's pages -- do not edit.  Shape:  `SiteSearchFile` in src/docs-components/docs-components.types.ts.",
      pages: this.pageFiles().map((path) => SiteSearchBuilder.page(path, readFileSync(join(this.site, path), "utf8")))
    }
  }

  /**
   * The text of `search.json`:  2-space JSON, but ONE section per line (a third of the size, and a diff still names
   * the section that changed).
   */
  text(): string {
    const file = this.build()
    const pages = file.pages.map((page) => {
      const { sections, ...head } = page
      const fields = Object.entries(head).map(
        ([key, value]) => `      ${JSON.stringify(key)}: ${JSON.stringify(value)}`
      )
      const lines = sections.map((section) => `        ${JSON.stringify(section)}`)
      const list = lines.length ? `[\n${lines.join(",\n")}\n      ]` : "[]"
      return `    {\n${[...fields, `      "sections": ${list}`].join(",\n")}\n    }`
    })
    return `{\n  "$comment": ${JSON.stringify(file.$comment)},\n  "pages": [\n${pages.join(",\n")}\n  ]\n}\n`
  }

  /**
   * Every page, relative to the site root:  the hand-written ones A-Z (`index.html` first), the component index,
   * then each component page A-Z.
   */
  pageFiles(): string[] {
    const top = this.html("").sort(
      (a, b) => Number(b === "index.html") - Number(a === "index.html") || a.localeCompare(b)
    )
    const components = this.html("components")
    return [
      ...top,
      ...components.filter((file) => file === "index.html").map((file) => `components/${file}`),
      ...components.filter((file) => file !== "index.html").map((file) => `components/${file}`)
    ]
  }

  /** One page's entry, from its file's text. */
  static page(path: string, html: string): SiteSearchPage {
    const { document } = parseHTML(html)
    const main = document.querySelector("main#main") ?? document.querySelector("main") ?? document.body
    const { sections, tabs } = PageOutline.sections(main as unknown as Element)
    const file = path.slice(path.lastIndexOf("/") + 1)
    const component = path.startsWith("components/") && file !== "index.html"
    const summary = document.querySelector('meta[name="description"]')?.getAttribute("content")?.trim()
    return {
      path,
      title: SiteSearchBuilder.pageTitle(document, main),
      ...(summary && { summary }),
      ...(component && { tag: file.replace(/\.html$/, "") }),
      ...(Object.keys(tabs).length && { tabs }),
      sections
    }
  }

  /** A page's title:  its `main`'s `data-toc-header`, else its `<title>` without the site's suffix. */
  private static pageTitle(document: Document, main: Element): string {
    const header = main.getAttribute("data-toc-header")?.trim()
    if (header) return header
    return (document.querySelector("title")?.textContent ?? "").trim().replace(SiteSearchBuilder.TITLE_SUFFIX, "")
  }

  /** The `.html` files of `folder` (relative to the site), A-Z;  none if it doesn't exist. */
  private html(folder: string): string[] {
    const path = join(this.site, folder)
    if (!existsSync(path)) return []
    return readdirSync(path)
      .filter((file) => file.endsWith(".html"))
      .sort()
  }
}
