/**
 * Shared types and constants for `$/ui/icons`:  the icon PACK format (`pack.js`) and the names around it.
 * - Runtime-light:  no imports, so node tooling (`tools/IconPackBuilder.ts`, `scripts/gen-icons.ts`) can import it
 *   by relative path, and the runtime service (`UI.icons`) by `$/ui/icons`.
 * - See `docs/icons.md` for the format and how names resolve.
 */

////////////////
// ## Pack index
////////////////

/**
 * A pack's index:  the `export default` of its `pack.js`, generated by `IconPackBuilder` and safe to hand-edit.
 * - Every SVG path is RELATIVE:  `<key>.svg` resolves against the pack's base, which defaults to the folder
 *   `pack.js` was loaded from.
 */
export type IconPackIndex = {
  /** unique id, e.g. `fa7-free`;  also usable as a name prefix (`fa7-free:bell`) */
  id: string
  /** human name, for the docs icon browser */
  label?: string
  /** licence / attribution line for the icons */
  license?: string
  /** applied to every entry that doesn't set its own */
  defaults?: IconPackDefaults
  /**
   * One entry per icon, keyed by its SVG path relative to the base, without `.svg`:  `solid/address-book`.
   * - The icon's name is the key's file name, dashes -> spaces (`address book`), plus its `alias`es.
   * - NOTE:  order matters when two entries claim the same name -- see `IconName`.
   */
  icons: Record<string, IconPackEntry>
}

/** Values every entry of a pack gets unless it sets its own. */
export type IconPackDefaults = {
  /** viewBox height */
  height?: number
  /** viewBox width */
  width?: number
}

/** One icon in a pack index. */
export type IconPackEntry = {
  /** viewBox width;  falls back to `defaults.width` */
  width?: number
  /** viewBox height;  falls back to `defaults.height` */
  height?: number
  /** more names for this icon (normalized like any name) -- how a hand-edit renames an icon */
  alias?: string | string[]
}

////////////////
// ## Built-in packs
////////////////

/**
 * Packs `@spell-app/ui` ships, served from `icon-packs/<id>/` next to the chunk that holds `BuiltInPacks`.
 * - `fa7-free`:  Font Awesome 7 Free solid + regular (`… outline`), plus a few extras;  the DEFAULT pack
 * - `fa7-brands`:  every Font Awesome 7 Free brand icon
 * - `fomantic`:  Fomantic-UI's icon names, pointing at the two FA folders
 */
export const BUILT_IN_ICON_PACKS = ["fa7-free", "fa7-brands", "fomantic"] as const

/** Id of a pack `@spell-app/ui` ships. */
export type BuiltInIconPack = (typeof BUILT_IN_ICON_PACKS)[number]

/** Pack the runtime adds by itself, unless a page replaces it (`only`). */
export const DEFAULT_ICON_PACK: BuiltInIconPack = "fa7-free"

/** File name of every pack's index. */
export const ICON_PACK_INDEX = "pack.js"

/** Separates a pack prefix from the icon name:  `lucide:bell`. */
export const ICON_PREFIX_SEPARATOR = ":"
