/* GENERATED by `yarn gen:markdown` (packages/ui/scripts/gen-markdown.ts):  NEVER edit. */

/** The markdown engine:  `render()` ~== `MD.render()` (`$/markdown`). */
declare const engine: {
  render(
    text: string,
    options?: {
      ui?: boolean
      headingIds?: boolean
      headingOffset?: number
      breaks?: boolean
      autolinks?: boolean
      tagfilter?: boolean
    }
  ): { html: string; headings: { level: number; text: string; id: string }[] }
}
export default engine
