/* GENERATED by `yarn gen:markdown` (packages/ui/scripts/gen-markdown.ts):  NEVER edit. */

// Import directly:  `SourceError` anchors this chunk to core (see gen-spell.ts)
import { SourceError } from "$/ui/runtime/runtime.types"

import engine from "./md.bundle.js"

if (typeof engine?.render !== "function") {
  throw new SourceError("MDBundle.ts:  md.bundle.js has no render();  run `yarn gen:markdown`", {
    cause: { kind: "render" }
  })
}

export default engine
