import { E } from "$/ui/core"

// Above the class:  the static `set` reads it while the class is defined
/** The name set used until told otherwise. */
const DEFAULT_SET = "cldr"

/****************
 * ### `EmojiData`
 * Emoji names => native Unicode emoji, loaded lazily in chunks, per NAME SET.
 * - Name sets (never merged):  `cldr`, the default (CLDR shortcodes, every emoji `emojibase-data` names:
 *   `thumbs_up`), and `fomantic` (Fomantic's own names with Fomantic's meanings:  `thumbsup`, `smile`, `dog` = 🐶).
 *   A translated set is another value of `names` (`es`, from emojibase's `es` data;  see `docs/translation.md`).
 * - Which set:  per `<ui-root emoji="fomantic">` for its subtree (`setFor(element)`, through `RootSettings`:
 *   the nearest root that sets one), else the PAGE's:  `EmojiData.use("fomantic")` from JS, `cldr` by default.
 *   Each set keeps its own loaded names, so two roots on one page can use different sets.  A page switch affects LATER
 *   lookups only:  an emoji already drawn keeps its glyph (a root's change redraws its own, `RootSettings.generation`).
 * - Data:  `./data/<set>/<chunk>.json`, one per first letter of the name (`0` for a digit),
 *   generated by `scripts/gen-emoji.ts` from `emojibase-data` (a dev-only dependency) and Fomantic's `@emoji-map`;
 *   a chunk is at most ~5 KB gzip.
 * - Loaded with `import()` on first use of a name in that chunk:  nothing is in `core` or in the emoji family's
 *   own chunk, and a page drawing `smile` fetches `s.json` only.  The module system is the cache;
 *   a failed load is a miss until the next `get()` (no retry storm:  one import per chunk at a time).
 * - STATIC throughout:  ONE emoji cache per page, shared by every `<ui-emoji>` and the static server render,
 *   so each chunk loads once, whoever asks.
 * - Import graph:  library-neutral apart from `E.RootSettings` (core), and no rendering.
 *   The family barrel exports it, for pages that pick a set or register names.
 ****************/
export class EmojiData {
  /**
   * Where a chunk's names come from instead of this module's own lazy `import()`s:  `(set, chunk) => names`.
   * - For a build that can't load ES modules lazily, e.g. the docs' single-file bundle on `file://`,
   *   which loads each chunk as a classic `<script>` (`packages/docs/tools/bundle-spell-ui.js`).
   *   Set it before the first lookup.
   */
  static chunkLoader?: (set: string, chunk: string) => Promise<Record<string, string>>

  ////////////////
  // ## The page's name set
  ////////////////

  /** The page's name set:  `cldr` unless `use()` says otherwise. */
  static get names(): string {
    return EmojiData.set
  }

  /** The PAGE's name set:  `use()`'s, else the default. */
  private static set: string = DEFAULT_SET

  /**
   * Use name set `names` (`cldr` or `fomantic`;  an unknown one means the default) for every LATER lookup on the page
   * (outside a `<ui-root emoji>`).  Loaded names of every set stay;  `register()`ed names apply to all.
   */
  static use(names: string | undefined) {
    EmojiData.set = EmojiData.validSet(names)
  }

  /** Back to the default set, every loaded name forgotten.  For tests and hot reload. */
  static reset() {
    EmojiData.set = DEFAULT_SET
    EmojiData.sets.clear()
  }

  /** The set `element` draws from:  its nearest `<ui-root emoji>`'s (`RootSettings`), else the page's. */
  static setFor(element: Element): string {
    const set = E.RootSettings.nearest(element, "emoji")
    return set === undefined ? EmojiData.set : EmojiData.validSet(set)
  }

  ////////////////
  // ## Names
  ////////////////

  /**
   * Canonical form of a name as authors write it:  trimmed, Fomantic's `:colons:` stripped,
   * camelCase split (`thumbsUp`, from JS), lower case, runs of spaces => `_` (`Thumbs Up` ~== `thumbs_up`).
   * Dashes stay:  some names have them (`blond-haired_woman`);  `loose()` drops them for the fallback.
   */
  static normalize(name: string): string {
    return name.trim().replace(COLONS, "").trim().replace(CAMEL, "$1_$2").toLowerCase().replace(SPACES, "_")
  }

  /**
   * A NORMALIZED name with no separators at all (`thumbsup`, `thumbs-up` => `thumbsup`):  the fallback key,
   * so a name works however its words are joined.  In the data, names that differ only in separators mean the same
   * emoji, except Fomantic's `icecream` (see `EmojiSetData.looseCache`).
   */
  static loose(name: string): string {
    return name.replace(SEPARATORS, "")
  }

  /** Chunk key of a NORMALIZED name:  its first letter, else `0`.  MUST match `scripts/gen-emoji.ts`. */
  static chunkFor(name: string): string {
    const first = name[0] ?? ""
    return LETTER.test(first) ? first : DIGIT_CHUNK
  }

  ////////////////
  // ## Lookups
  ////////////////

  /** The emoji for `name` in `set` (default the page's) if it's already known (loaded or registered).  Synchronous. */
  static peek(name: string | undefined, set: string = EmojiData.set): string | undefined {
    return name ? EmojiData.emojiFor(EmojiData.normalize(name), set) : undefined
  }

  /**
   * The emoji for `name` in `set` (default the page's), loading its chunk if needed;  `undefined` for an unknown name.
   * - NEVER rejects.
   * - SIDE EFFECT:  caches the whole chunk.
   */
  static async get(name: string | undefined, set: string = EmojiData.set): Promise<string | undefined> {
    if (!name) return undefined
    const key = EmojiData.normalize(name)
    const known = EmojiData.emojiFor(key, set)
    if (known !== undefined || !key) return known
    const chunk = EmojiData.chunkFor(key)
    if (!EmojiData.dataFor(set).loaded.has(chunk)) await EmojiData.load(set, chunk)
    return EmojiData.emojiFor(key, set)
  }

  /**
   * Load the chunks of every name in `names`, in each of `sets` (default:  every set that ships),
   * so later `peek()`s find them synchronously.
   * - NEVER rejects.
   * - For the static server render (`$/ui/static`), which is synchronous:  see `UIEmoji.preload()`.
   */
  static async preload(names: Iterable<string>, sets: Iterable<string> = SETS): Promise<void> {
    const list = [...new Set(names)]
    const loads: Promise<unknown>[] = []
    for (const set of sets) for (const name of list) loads.push(EmojiData.get(name, set))
    await Promise.all(loads)
  }

  /** Add (or override) one emoji without a request, e.g. an app's own name for a sequence.  Applies to any set. */
  static register(name: string, emoji: string) {
    const key = EmojiData.normalize(name)
    EmojiData.registered.set(key, emoji)
    EmojiData.registeredLoose.set(EmojiData.loose(key), emoji)
  }

  ////////////////
  // ## Internal
  ////////////////

  /** Set => its loaded names (`EmojiSetData`). */
  private static readonly sets = new Map<string, EmojiSetData>()

  /** `register()`ed names:  they survive a switch and apply to any set, ahead of its own names. */
  private static readonly registered = new Map<string, string>()

  /** The same, keyed by `loose()`. */
  private static readonly registeredLoose = new Map<string, string>()

  /** `<set>/<chunk>` => its load, so each chunk is requested once at a time. */
  private static readonly loads = new Map<string, Promise<void>>()

  /** `set`'s loaded names, created on first use. */
  private static dataFor(set: string): EmojiSetData {
    let data = EmojiData.sets.get(set)
    if (!data) {
      data = { cache: new Map(), looseCache: new Map(), loaded: new Set() }
      EmojiData.sets.set(set, data)
    }
    return data
  }

  /** A NORMALIZED name's emoji in `set`:  registered first, then the exact name, else the same words joined any way. */
  private static emojiFor(key: string, set: string): string | undefined {
    const { cache, looseCache } = EmojiData.dataFor(set)
    const loose = EmojiData.loose(key)
    return (
      EmojiData.registered.get(key) ?? cache.get(key) ?? EmojiData.registeredLoose.get(loose) ?? looseCache.get(loose)
    )
  }

  /** `names` if it is a set we ship data for, else the default. */
  private static validSet(names: string | undefined): string {
    const set = names?.trim().toLowerCase()
    return set && SETS.has(set) ? set : DEFAULT_SET
  }

  /**
   * Load chunk `chunk` of `set` once.
   * - NEVER rejects:  a failure is forgotten, so a later `get()` tries again.
   */
  private static load(set: string, chunk: string): Promise<void> {
    const id = `${set}/${chunk}`
    let load = EmojiData.loads.get(id)
    if (!load) {
      const own = LOADERS[`./data/${id}.json`]
      if (!own) return Promise.resolve()
      const names = EmojiData.chunkLoader ? EmojiData.chunkLoader(set, chunk) : own().then((module) => module.default)
      load = names
        .then((names) => {
          const { cache, looseCache, loaded } = EmojiData.dataFor(set)
          for (const [name, emoji] of Object.entries(names)) {
            if (!cache.has(name)) cache.set(name, emoji)
            const loose = EmojiData.loose(name)
            if (!looseCache.has(loose)) looseCache.set(loose, emoji)
          }
          loaded.add(chunk)
        })
        .catch(() => undefined)
        .finally(() => EmojiData.loads.delete(id))
      EmojiData.loads.set(id, load)
    }
    return load
  }
}

/**
 * One name set's loaded names.
 * - `looseCache` is the fallback when the exact name misses;  first name in wins -- chunks list names sorted,
 *   and `_` sorts before letters, so the underscored spelling wins a clash.  In `cldr` there is none;  in `fomantic`,
 *   `ice-cream` / `IceCream` ~== `ice_cream` 🍨, while an exact `icecream` stays 🍦.
 */
type EmojiSetData = {
  /** name => emoji */
  readonly cache: Map<string, string>
  /** `loose()` name => emoji:  the fallback when the exact name misses */
  readonly looseCache: Map<string, string>
  /** chunks loaded */
  readonly loaded: Set<string>
}

/**
 * One loader per data chunk (`./data/cldr/a.json` ...), from `import.meta.glob`.
 * - Why not ``import(`./data/${set}/${chunk}.json`)``:  a variable path makes Rolldown add its dynamic-import helper
 *   to this family's chunk (`yarn measure`'s `coreOutsideCore` check);  the glob compiles to one static `import()`
 *   per file, with no helper.
 */
const LOADERS = import.meta.glob<{ default: Record<string, string> }>("./data/*/*.json")

/** The name sets that ship, from the data folders. */
const SETS = new Set(Object.keys(LOADERS).map((path) => path.split("/")[2]!))

/** Fomantic's `:name:` colons. */
const COLONS = /^:+|:+$/g

/** Runs of whitespace inside a name. */
const SPACES = /\s+/g

/** A camelCase word boundary:  a lower-case letter or digit, then a capital. */
const CAMEL = /([a-z0-9])([A-Z])/g

/** Every way a name's words may be joined. */
const SEPARATORS = /[_-]/g

/** A chunk letter. */
const LETTER = /^[a-z]$/

/** Chunk of names starting with anything but a letter. */
const DIGIT_CHUNK = "0"
