/* GENERATED by `yarn gen:spell` (packages/ui/scripts/gen-spell.ts):  NEVER edit. */

/** Spell's highlighter (en):  highlight.js-scoped spans of a spell snippet. */
declare const highlighter: { highlight(code: string): { start: number; end: number; kind: string }[] }
export default highlighter
