/* GENERATED by `yarn gen:spell` (packages/ui/scripts/gen-spell.ts):  NEVER edit. */

// Import directly:  `SourceError` anchors this chunk to core (see gen-spell.ts)
import { SourceError } from "$/ui/runtime/runtime.types"

import highlighter from "./spell.en.bundle.js"

if (typeof highlighter?.highlight !== "function") {
  throw new SourceError("spell.en.ts:  spell.en.bundle.js has no highlight();  run `yarn gen:spell`", {
    cause: { kind: "render" }
  })
}

export default highlighter
